apiVersion: apps/v1
kind: Deployment
metadata:
  name: dungeon-crawler-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dungeon-backend
  template:
    metadata:
      labels:
        app: dungeon-backend
    spec:
      containers:
      - name: backend-container
        image: your-backend-image:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"   # Minimum memory the container will get
            cpu: "250m"       # Minimum CPU the container will get
          limits:
            memory: "256Mi"   # Maximum memory the container can use
            cpu: "500m"       # Maximum CPU the container can use
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dungeon-crawler-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dungeon-frontend
  template:
    metadata:
      labels:
        app: dungeon-frontend
    spec:
      containers:
      - name: frontend-container
        image: your-frontend-image:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"    # Minimum memory the container will get
            cpu: "100m"       # Minimum CPU the container will get
          limits:
            memory: "128Mi"   # Maximum memory the container can use
            cpu: "200m"       # Maximum CPU the container can use
